### ISSUE TITLE
Two column timeline

### ISSUE THREAD

**Issue by rrjanbiah** [thegamenicorus/react-native-timeline-listview#1]
@thegamenicorus Thanks a lot for the nice library

Can you please provide some hint about getting two column timeline as in https://dribbble.com/shots/600575-Timeline or https://dribbble.com/shots/1085018-Today

TIA

**Comment by thegamenicorus** [comment]
Hello @rrjanbiah 

I've released react-native-timeline-listview v.0.2.0 today. There are new props: 'columnFormat' that can be 'single-column-left'(by default), 'single-column-right' and 'two-column' (from your request).

![simulator screen shot apr 6 2560 be 5 05 32 pm](https://cloud.githubusercontent.com/assets/21040043/24749638/0515f210-1aee-11e7-82af-082d93efb618.png)

you can take a look, [here](https://github.com/thegamenicorus/react-native-timeline-listview/blob/master/examples/Example/pages/twoColumnExample.js)

Thank you for your request :D
Cheer!

**Comment by rrjanbiah** [comment]
@thegamenicorus Many thanks for the awesome news and work!
