### ISSUE TITLE
iOS - Icon not loading sometimes

### ISSUE THREAD

**Issue by AndrePech** [thegamenicorus/react-native-timeline-listview#16]
This library is awesome, thanks.

I noticed that sometimes, my icon does not render, leaving the icon and the circle completely empty, they show up after re-rendering the screen...

I am setting the icon in the following way, in the Timeline props:
`icon = {require('./path_to_icon.png'}`

I will try setting the icon in the data object...
Sorry if i am missing something.

**Comment by thegamenicorus** [comment]
Hi @AndrePech,I'm glad you like it.

For the issue could you please provide more detail about your testing device.

**Comment by AndrePech** [comment]
Sorry for the delay, hehe, I have tested it a lot in many devices, iOS and Android, they all work fine.
I believe the problem was only happening in the simulator.

**Comment by thegamenicorus** [comment]
Ok, Happy coding 😄
