### ISSUE TITLE
How to add multiple description in one event

### ISSUE THREAD

**Issue by sihitejulio** [thegamenicorus/react-native-timeline-listview#17]
Hi, i can add multi description in one date like
 18 Aug 2017 - To Destination one
                      - To Destination Two
 19 Aug 2017 - To Cafe
                      - To Office

**Comment by duycoder** [comment]
Well, you have to do it your self. Go go **~/node_modules/react-native-timeline-listview/lib/index.js** => go to **_renderDetail** function at  **line 206**.add some more properties that you want :))

**Comment by thegamenicorus** [comment]
Hi @sihitejulio 

you can use renderDetail prop. please see https://github.com/thegamenicorus/react-native-timeline-listview/blob/master/examples/Example/pages/overrideRenderExample.js
