### ISSUE TITLE
fontFamily not work for titleStyle

### ISSUE THREAD

**Issue by smrd1998** [thegamenicorus/react-native-timeline-listview#61]
i cant set font for the timeline title style (other style like color work but fontFamily not working) im sure my font is ok because i use it every where in my app (it just not work in time line)
good luck

**Comment by hanie-hadadi** [comment]
you have to set `fontWeight `to normal something like this : 
`titleStyle={{fontWeight: "normal",fontFamily:'BKoodakBold',textAlign: 'right'}}`

**Comment by hanie-hadadi** [comment]
> i cant set font for the timeline title style (other style like color work but fontFamily not working) im sure my font is ok because i use it every where in my app (it just not work in time line)
> good luck

you have to set `fontWeight `to normal something like this : 
`titleStyle={{fontWeight: "normal",fontFamily:'BKoodakBold',textAlign: 'right'}}`
