### ISSUE TITLE
ListView has been removed from React Native

### ISSUE THREAD

**Issue by SnehalAgrawal** [thegamenicorus/react-native-timeline-listview#69]
Can you please update the library? as many of my readers are reporting the bug in the library at https://aboutreact.com.

I think the problem is related to the Listview being deprecated in the React Native 0.56 and your library has used the ListView. Can you please shift it to the FlatList?

It is showing the following error:

E | ReactNativeJS ▶︎ ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`.
E | ReactNativeJS ▶︎ Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by ebwinters** [comment]
I wrote a hotfix PR for this issue, and am using it successfully in my application. #70

**Comment by nadernt** [comment]
> Can you please update the library? as many of my readers are reporting the bug in the library at https://aboutreact.com.
> 
> I think the problem is related to the Listview being deprecated in the React Native 0.56 and your library has used the ListView. Can you please shift it to the FlatList?
> 
> It is showing the following error:
> 
> E | ReactNativeJS ▶︎ ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`.
> E | ReactNativeJS ▶︎ Module AppRegistry is not a registered callable module (calling runApplication)

To solve this issue, go to [this](https://github.com/Eugnis/react-native-timeline-flatlist) repository and replace all of the contents in the lib folder with the current repository's lib folder. All the examples will work with no issue.

**Comment by SnehalAgrawal** [comment]
Thank you @nadernt. Are you the maintainer of that library?

**Comment by nadernt** [comment]
Hi Snehal, no I don't. It is a good idea to update this repository because the mentioned repository looks a fork of react-native-timeline-listview.

**Comment by SnehalAgrawal** [comment]
@nadernt Ok. Thank you for the reference to the new library. It is working fine.
https://aboutreact.com/react-native-timeline-listview/
