### ISSUE TITLE
Update required to 0.60.5

### ISSUE THREAD

**Issue by joaodematejr** [thegamenicorus/react-native-timeline-listview#71]
No longer works in version react-native 0.60.5

**Comment by SnehalAgrawal** [comment]
You can see #69

**Comment by SnehalAgrawal** [comment]
You can use react-native-timeline-flatlist
It is the same with  with flatlist instead of listview.
Here is the example https://aboutreact.com/react-native-timeline-listview/

**Comment by joaodematejr** [comment]
OK thank you.
