### ISSUE TITLE
ERROR    Invariant Violation: ListView has been removed from React Native.

### ISSUE THREAD

**Issue by fangx4** [thegamenicorus/react-native-timeline-listview#76]
[Tue Aug 11 2020 11:19:53.517]  ERROR    Invariant Violation: ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`.
[Tue Aug 11 2020 11:19:53.518]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Aug 11 2020 11:19:53.518]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by johnchen** [comment]
我也遇到这个问题了，你那解决了吗

**Comment by fangx4** [comment]
> 我也遇到这个问题了，你那解决了吗

没有， 可以换另一个用
https://github.com/Eugnis/react-native-timeline-flatlist
