### ISSUE TITLE
Bind props render methods to this

### ISSUE THREAD

**Issue by mielvds** [thegamenicorus/react-native-timeline-listview#8]
The `renderTime`, `renderCircle` and `renderDetail` that you can override do not bound `this`  to the component instance itself. This makes a reuse of the original render functions impossiblen which is useful if you want to add conditional rendering. Also, you cannot reach `this.state`, which, for instance, causes issues with positioning the circle.

I propose to use

    this.renderTime = (this.props.renderTime?this.props.renderTime:this._renderTime).bind(this)
    this.renderDetail = (this.props.renderDetail?this.props.renderDetail:this._renderDetail).bind(this)
    this.renderCircle = (this.props.renderCircle?this.props.renderCircle:this._renderCircle).bind(this)

**Comment by thegamenicorus** [comment]
Hello @mielvds 

Thank you for your help. I'll release new version soon. 😃

**Comment by thegamenicorus** [comment]
update in v.0.2.2

Thanks again 👍
