### ISSUE TITLE
Render Circle displays icons to far right of 2 column

### ISSUE THREAD

**Issue by Esko918** [thegamenicorus/react-native-timeline-listview#9]
Im trying to display a custom view for the circle in the middle of the two column timeline. I use the renderCircle method and i can see that my custom view is being rendered. THe only issue is that the custom circle is being rendered to the far right of the screen instead of down the middle line that is rendered. Do i maybe need to change more styles or is this a bug?

**Comment by alburdette619** [comment]
https://github.com/thegamenicorus/react-native-timeline-listview#shift-problem

**Comment by thegamenicorus** [comment]
Hello @Esko918 

Can you fix this problem?

**Comment by dsah** [comment]
I am still having this issue...

**Comment by shubhamverma27** [comment]
+1 
Stil facing this issue
